### ISSUE TITLE
프로필 화면 구현

### ISSUE THREAD

**Issue by Haemin-Park** [woowa-techcamp-2022/android-repo-08#37]

**Comment by aurora32s** [comment]
[이슈]
star 의 개수를 받아오기 위해서는 모든 페이지의 데이터를 받아와 개수를 더해주는 방법으로 해야함

1. while문으로 하나씩 순차적으로 요청(async/await 사용)
  -> 시간이 너무 오래 걸림
2. while문으로 하나씩 병렬적으로 요청(launch 사용)
  -> 마지막 페이지 요청을 response 받기 전에, 다음 페이지들 요청이 먼저 가버려서 불필요한 요청까지 수행

**Comment by aurora32s** [comment]
[궁금증]
Nullabel 프로퍼티에 null 값을 넣어주면 default value로 초기화가 될까?
